# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LUSZiFjf2n1lB1XDNiLJiaFMjNlh7nkO
"""
! pip install pandas scikit-learn streamlit
! streamlit run app.py

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import streamlit as st
import re

# Load datasets
train_df = pd.read_csv('/content/Training.csv')
test_df = pd.read_csv('/content/Testing.csv')
doctors_df = pd.read_csv('/content/doctors_dataset.csv', header=None, names=['Doctor', 'Link'])

# Map diseases to specializations (extend as needed)
disease_specialization_map = {
    'Fungal infection': 'Dermatologist',
    'Allergy': 'Allergist',
    'GERD': 'Gastroenterologist',
    'Chronic cholestasis': 'Gastroenterologist',
    'Drug Reaction': 'General Physician',
    'Peptic ulcer diseae': 'Gastroenterologist',
    'AIDS': 'Infectious Disease Specialist',
    'Diabetes ': 'Endocrinologist',
    'Gastroenteritis': 'Gastroenterologist',
    'Bronchial Asthma': 'Pulmonologist',
}

# Prepare model
X = train_df.drop(columns=['prognosis'])
y = train_df['prognosis']
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X, y_encoded)

# Predict disease from symptom list
def predict_disease(symptom_input):
    input_vector = [1 if symptom in symptom_input else 0 for symptom in X.columns]
    pred = model.predict([input_vector])
    return label_encoder.inverse_transform(pred)[0]

# Recommend a doctor
def fetch_doctor(disease):
    specialization = disease_specialization_map.get(disease, 'General Physician')
    matched = doctors_df[doctors_df['Doctor'].str.contains(specialization, case=False, na=False)]
    if not matched.empty:
        doc = matched.sample(1).values[0]
    else:
        doc = doctors_df.sample(1).values[0]
    return doc[0], doc[1]

# Extract symptoms from user message
def extract_symptoms(text):
    words = re.findall(r'\w+', text.lower())
    return [symptom for symptom in X.columns if symptom.replace('_', ' ') in ' '.join(words)]

# Streamlit UI
st.set_page_config(page_title='AI Health Chatbot')
st.title("💬 Healthcare Chatbot")
st.markdown("Describe your symptoms in natural language, and I'll try to help you.")

user_input = st.text_area("What's going on? Describe your symptoms:")

if st.button("Get Advice"):
    if user_input.strip():
        extracted_symptoms = extract_symptoms(user_input)
        if extracted_symptoms:
            disease = predict_disease(extracted_symptoms)
            doc_name, doc_link = fetch_doctor(disease)
            st.success(f"🩺 It sounds like you may have **{disease}**.")
            st.info(f"👨‍⚕️ You should consult: [{doc_name}]({doc_link})")
        else:
            st.warning("Sorry, I couldn't detect symptoms from your message. Try to describe them more clearly.")
    else:
        st.warning("Please type your symptoms above.")

